API_V1_PREFIX = "/api/v1"

DEFAULT_PAGE_SIZE = 50
MAX_PAGE_SIZE = 200

DEFAULT_GEOFENCE_RADIUS = 500

NO_HEART_RATE_SECONDS = 30
NO_MOVEMENT_SECONDS = 60
BATTERY_CRITICAL_LEVEL = 10

TELEMETRY_WINDOW_SECONDS = 300
MIN_SAMPLES_FOR_VERIFICATION = 100
